<?php

namespace ImageGallery\ImageGalleryBundle\Entity\Repository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAlbums($limit = null)
    {
        $qb = $this->createQueryBuilder('a')->select('a')->addOrderBy('a.created', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
