<?php

namespace ImageGallery\ImageGalleryBundle\Entity\Repository;

/**
 * ImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getImagesForAlbum($albumId, $limit = 10)
    {
        $qb = $this->createQueryBuilder('i')
            ->select('i')
            ->where('i.parent = :parent_id')
            ->addOrderBy('i.created')
            ->setParameter('parent_id', $albumId)
            ->setMaxResults($limit);

        return $qb->getQuery();
    }
}
